openapi: "3.0.0"
info:
  title: Shoppeng API
  version: "1.0"
paths: 
  /products:
    description: The products catalog
    get:
      summary: Search for products 
      description: | 
        Search for products in catalog 
        using a free query parameter
      responses:
        "200":
          description: |
            Products matvhing free query parameter 


  
